# Generated by Django 5.2.1 on 2025-06-10 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_item'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
