# Generated by Django 5.2.1 on 2025-06-11 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carbrand',
            name='photo_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='carbrand',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='carbrand',
            name='logo_url',
            field=models.URLField(),
        ),
    ]
