# Generated by Django 5.2.1 on 2025-06-11 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_carbrand_photo_url_alter_carbrand_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carbrand',
            name='logo_url',
        ),
        migrations.AddField(
            model_name='carbrand',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='brand_logos/'),
        ),
    ]
