# Generated by Django 5.2.1 on 2025-06-11 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_carbrand_logo_url_carbrand_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='carbrand',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
